# path to root directory
# this requires PROJECT_ROOT environment variable to exist 
# run `export PROJECT_ROOT=$(pwd)` to set to current dir
# verify PROJECT_ROOT was updated by running `echo $PROJECT_ROOT`
root_dir: ${oc.env:PROJECT_ROOT}

# path to data directory
data_dir: ${paths.root_dir}/data/

# path to logging directory
log_dir: ${paths.root_dir}/logs/

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}

# paths specific to pdb data
pdb_raw_dir: ${paths.data_dir}/pdb/raw
pdb_processed_dir: ${paths.data_dir}/pdb/processed
ccd_path: ${paths.pdb_raw_dir}/ccd/components.cif.gz
ccd_atoms_map_path: ${paths.pdb_processed_dir}/ccd_atoms.json
lmdb_path: ${paths.pdb_processed_dir}/pdb_dataset.lmdb